model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: gt
    cond_stage_key_1: sketch
    cond_stage_key_2: texture
    image_size: 32
    channels: 4
    monitor: val/loss_simple_ema
    cond_stage_trainable: True 
    probability_of_discard: 0.1
    scale_1: 1.1
    scale_2: 1.5
    style_loss_weight: 1.0
    is_use_style_loss: True 
    cond_stage_config: 
      target: ldm.modules.diffusionmodules.Fusion.bFMFusion
      params:
        sketch_nc: 1
        texture_nc: 3
        ngf: 144
        norm_layer: torch.nn.BatchNorm2d
        bottleneck_depth: 100
        num_resblocks: 0
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 288
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: /workspace/my-latent-diffusion-add-in-upsample/models/first_stage_models/vq-f8/model.ckpt
        embed_dim: 4
        n_embed: 16384
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: 
          - 32
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    
    vgg_loss_config:
      target: ldm.modules.diffusionmodules.vgg_loss.VGG_Loss
      params:
        perceptual_layers: ['relu1_2',"relu2_2",'relu3_2','relu4_2','relu5_2']
        style_layers:  ["relu3_2", 'relu4_2']

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: false
    train:
      target: dataset.MyDataSetTrain
      params:
        size: 256
        path: /workspace/my-latent-diffusion-add-in-upsample/my_latent_diffusion_big_dataset
    validation:
      target: dataset.MyDataSetValidation
      params:
        size: 256
        path: /workspace/my-latent-diffusion-add-in-upsample/my_latent_diffusion_big_dataset


lightning:
  trainer:
    benchmark: True
    accumulate_grad_batches: 6
    max_epochs: 26
    choose_logger: wandb
  
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      save_top_k: 1 
      save_last: True 

  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 4
        increase_log_steps: False

